GET http://localhost:8080
###
GET http://localhost:8080/welcome
###
GET http://localhost:8080/method
###
GET http://localhost:8080/products
###
GET http://localhost:8080/products?name=name
###
GET http://localhost:8080/products/3
###
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "New"
}
###
PUT http://localhost:8080/products/1
Content-Type: application/json

{
  "name": "New Laptop"
}